[build-system]
requires = ["setuptools" ,"setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]

[tool.poetry]
name = "my_package"
version = "0.1.0"
description = "Example package"

[tool.poetry.dependencies]