[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "docker-injector"
version = "0.1.0"
description = "Docker Injector"
authors = ["Alexander MK <github-alex@xxl.cx>"]

[tool.poetry.dependencies]
python = "^3.11"